# Generated by Django 3.2.3 on 2021-05-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalimage',
            options={},
        ),
        migrations.RenameField(
            model_name='additionalimage',
            old_name='bb',
            new_name='ai',
        ),
    ]
