# Generated by Django 3.2.3 on 2021-05-15 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210515_1839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalImage',
        ),
    ]
